### PR TITLE
ADDED STRONG RE-HASHABLE TECHNIQUES

### PR DESCRIPTION
**Pull request by SKR301**
Need more testing...
Checked from 1 to 1000 for 4 char salt. No issue observed.

Doesn't quite work for long salt value. Might need to breakup salt in pieces.

### CODE REVIEW

**Comment by SKR301** [comment]
Doesn't quite work for long salt value. Might need to breakup salt in pieces.

**Comment by SKR301** [comment]
Results in duplicate hash. Not that suitable!

**Comment by SKR301** [comment]
**MOD_INV** method works epically ; )

**Comment by norkator** [comment]
this is too complicated and output is too long. I merge this but it still won't cut the default use case.

**Pull request merged**
